# Generated by Django 4.2.4 on 2023-10-15 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст обращения')),
                ('kind', models.CharField(blank=True, choices=[('None', 'Обозначьте статус задачи'), ('Нерешенные', 'Нерешенные'), ('Решенные', 'Решенные'), ('Замороженные', 'Замороженные')], default='Нерешенные', max_length=50, null=True, verbose_name='Тип объявления')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['kind', '-created'],
            },
        ),
    ]
