# Generated by Django 5.0.7 on 2024-08-01 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
            },
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Нескольких типов бустов', 'Нескольких типов бустов'), ('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3')], default='Нескольких типов бустов', max_length=50, verbose_name='Тип буста')),
                ('player', models.ManyToManyField(related_name='boots', to=settings.AUTH_USER_MODEL, verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Бутс',
                'verbose_name_plural': 'Бутсы',
            },
        ),
        migrations.CreateModel(
            name='PlayerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerlevels', to='progress.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerlevels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игрок-Уровень',
                'verbose_name_plural': 'Общая таблица связей игрок-уровень',
            },
        ),
        migrations.CreateModel(
            name='PlayerPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerprize', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerprize', to='progress.prize')),
            ],
            options={
                'verbose_name': 'Игрок-Приз',
                'verbose_name_plural': 'Общая таблица связей игрок-приз',
            },
        ),
        migrations.CreateModel(
            name='LevelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelprize', to='progress.level')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelprize', to='progress.prize')),
            ],
            options={
                'verbose_name': 'Уровень-Приз',
                'verbose_name_plural': 'Общая таблица связей уровень-приз',
            },
        ),
    ]
