# Generated by Django 4.2.7 on 2023-11-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0009_remove_personage_animators_for_years'),
        ('age', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='animators_for_years',
            field=models.ManyToManyField(blank=True, related_name='for_age', to='personage.personage'),
        ),
    ]
