# Generated by Django 4.2.7 on 2023-12-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0013_alter_kombo_image_alter_personage_image'),
        ('age', '0002_age_animators_for_years'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name': 'Программа по возрастам', 'verbose_name_plural': 'Программы по возрастам'},
        ),
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.CharField(choices=[('choises', 'choises'), ('1_4', 'Animators for 1-4 years'), ('5_9', 'Animators for 5-9 years'), ('10_14', 'Animators for 10-14 years')], default='choises', max_length=50, verbose_name='Возраст на выбор'),
        ),
        migrations.AlterField(
            model_name='age',
            name='animators_for_years',
            field=models.ManyToManyField(blank=True, related_name='for_age', to='personage.personage', verbose_name='Аниматоры для выбранного возраста'),
        ),
    ]
