# Generated by Django 4.2.5 on 2023-09-27 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('us', '0003_profile_fronzenkind_profile_resolverkind_and_more'),
        ('tic', '0002_alter_ticket_options_alter_ticket_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('body', models.TextField(verbose_name='Текст сообщения')),
                ('kind', models.CharField(blank=True, choices=[('Непрочитано', 'Непрочитано'), ('Прочитано', 'Прочитано')], default='Непрочитано', max_length=50, null=True, verbose_name='Статус сообщения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='us.profile')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tic.ticket')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['kind', '-created'],
            },
        ),
    ]
