# Generated by Django 4.2.7 on 2023-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('choises', 'choises'), ('150 руб', '150 руб'), ('210 руб', '210 руб'), ('330 руб', '330 руб'), ('430 руб', '430 руб')], default='choises', max_length=50)),
                ('time', models.CharField(choices=[('choises', 'choises'), ('60 минут', '60 минут'), ('90 минут', '90 минут')], default='choises', max_length=50)),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
        ),
    ]
