# Generated by Django 4.2.7 on 2023-12-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Название'),
        ),
    ]
