# Generated by Django 4.2.7 on 2023-12-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_price_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Program',
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
    ]
