# Generated by Django 4.2.7 on 2023-12-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_rename_price_program_alter_program_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.CharField(choices=[('choises', 'choises'), ('150 руб', '150 руб'), ('210 руб', '210 руб'), ('330 руб', '330 руб'), ('430 руб', '430 руб')], default='choises', max_length=50, verbose_name='Выбор цены'),
        ),
        migrations.AlterField(
            model_name='program',
            name='time',
            field=models.CharField(choices=[('choises', 'choises'), ('60 минут', '60 минут'), ('90 минут', '90 минут')], default='choises', max_length=50, verbose_name='Выбор времени'),
        ),
    ]
