# Generated by Django 4.2.5 on 2023-09-25 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('None', 'Обозначьте статус задачи'), ('b', 'Пользователь'), ('c', 'Соппорт')], default='b', max_length=5, null=True, verbose_name='Роль')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Электронная почта')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('username', models.CharField(blank=True, default='Любопытная булочка', max_length=50, null=True, verbose_name='Имя пользователя')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('intro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Обо мне')),
                ('image', models.ImageField(blank=True, default='us_images/default.jpg', null=True, upload_to='us_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
            },
        ),
    ]
