# Generated by Django 4.2.5 on 2023-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fronzenKind',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resolverKind',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='unresolverKind',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
