# Generated by Django 4.2.7 on 2024-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя поста')),
                ('text', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Текст поста')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('activity', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('changes', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-created_at',),
            },
        ),
    ]
