# Generated by Django 4.2.7 on 2024-07-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('author', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Автор книги')),
                ('year', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Год издания')),
                ('status', models.CharField(choices=[('В наличии', 'В наличии'), ('Выдана', 'Выдана')], default='В наличии', max_length=50, verbose_name='Статус книги')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
