# Generated by Django 4.2.5 on 2023-09-25 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст обращения')),
                ('kind', models.CharField(blank=True, choices=[('None', 'Обозначьте статус задачи'), ('a', 'Нерешенные'), ('b', 'Решенные'), ('c', 'Замороженные')], default='a', max_length=5, null=True, verbose_name='Тип объявления')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='us.profile')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['-created'],
            },
        ),
    ]
