# Generated by Django 4.2.5 on 2023-09-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['kind', '-created'], 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='kind',
            field=models.CharField(blank=True, choices=[('None', 'Обозначьте статус задачи'), ('Нерешенные', 'Нерешенные'), ('Решенные', 'Решенные'), ('Замороженные', 'Замороженные')], default='Нерешенные', max_length=50, null=True, verbose_name='Тип объявления'),
        ),
    ]
