# Generated by Django 4.2.7 on 2023-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Администратор', 'Администратор'), ('Аниматор', 'Аниматор')], default='Пользователь', max_length=50),
        ),
    ]
