# Generated by Django 4.2.7 on 2023-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0007_personage_animators_1_4_years_and_more'),
        ('user', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_likes',
            field=models.ManyToManyField(blank=True, related_name='who_liked', to='personage.personage'),
        ),
    ]
