# Generated by Django 4.2.7 on 2023-11-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_my_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
