# Generated by Django 4.2.7 on 2023-11-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_username_profile_name_remove_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='full_name',
        ),
    ]
