# Generated by Django 4.2.7 on 2023-11-23 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_name_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Некорректный формат телефона', regex='^\\+?7[-. ]?\\d{5,12}$')]),
        ),
    ]
