# Generated by Django 4.2.7 on 2023-12-14 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0013_alter_kombo_image_alter_personage_image'),
        ('user', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_avatar_full_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_likes',
            field=models.ManyToManyField(blank=True, related_name='who_liked', to='personage.personage', verbose_name='Мои лайки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='my_orders', to=settings.AUTH_USER_MODEL, verbose_name='Мои заказы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Некорректный формат телефона', regex='^\\+?7[-. ]?\\d{5,12}$')], verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Администратор', 'Администратор'), ('Аниматор', 'Аниматор')], default='Пользователь', max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тикток'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
