# Generated by Django 4.2.7 on 2023-12-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_full_name_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
