# Generated by Django 4.2.7 on 2023-11-24 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_recipient_animators',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animator_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказ на аниматора'),
        ),
    ]
