# Generated by Django 4.2.7 on 2023-11-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0012_alter_kombo_image_alter_personage_image'),
        ('order', '0002_alter_order_to_recipient_animators'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kombo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='personage.kombo', verbose_name='Комбо'),
        ),
        migrations.AddField(
            model_name='order',
            name='personage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='personage.personage', verbose_name='Персонаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
