# Generated by Django 4.2.7 on 2023-12-08 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_a_call',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.notification')),
                ('phone_number', models.CharField(max_length=12)),
                ('time_to_call', models.CharField(choices=[('В течении получаса', 'В течении получаса'), ('Через один час', 'Через один час'), ('Через два часа', 'Через два часа')], default='В течении получаса', max_length=50, verbose_name='Желаемое время звонка')),
                ('info_for_users', models.CharField(default='Администратор может вам набрать с 9.00 да 18.00', max_length=50)),
                ('from_creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_order_a_call', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('order.notification',),
        ),
    ]
