# Generated by Django 4.2.7 on 2023-12-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_a_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_a_call',
            name='phone_number',
        ),
    ]
