# Generated by Django 4.2.7 on 2023-12-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_a_call_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_a_call',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
