# Generated by Django 4.2.7 on 2023-12-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_a_call_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
