# Generated by Django 4.2.7 on 2023-12-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_rename_price_program_alter_program_options'),
        ('order', '0009_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='price.program', verbose_name='Программа'),
        ),
    ]
