# Generated by Django 4.2.7 on 2023-12-12 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_alter_order_to_recipient_animators'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_recipient_two_animators',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animator_two_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказ на второго аниматора'),
        ),
    ]
