# Generated by Django 4.2.7 on 2023-12-12 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0012_order_to_recipient_two_animators'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_recipient_three_animators',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animator_three_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказ на третьего аниматора'),
        ),
    ]
