# Generated by Django 4.2.7 on 2023-12-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0012_alter_kombo_image_alter_personage_image'),
        ('order', '0013_order_to_recipient_three_animators'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='personage_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_for_three', to='personage.personage', verbose_name='Третий персонаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='personage_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_for_two', to='personage.personage', verbose_name='Второй персонаж'),
        ),
    ]
