# Generated by Django 4.2.7 on 2023-12-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_tasks_options_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_a_call',
            options={'verbose_name': 'Заказ на звонок администратора', 'verbose_name_plural': 'Заказы на звонок администратора'},
        ),
    ]
