# Generated by Django 4.2.7 on 2023-11-11 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='personage_images/default.jpg', null=True, upload_to='personage_images', verbose_name='Фото')),
                ('activity', models.BooleanField(default=True, verbose_name='Активность')),
                ('life_size_puppet', models.BooleanField(default=False, verbose_name='Ростовая кукла')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
    ]
