# Generated by Django 4.2.7 on 2023-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personage',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
    ]
