# Generated by Django 4.2.7 on 2023-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0006_remove_personage_creator_personage_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='personage',
            name='animators_1_4_years',
            field=models.BooleanField(default=False, verbose_name='Аниматоры для 1-4 года'),
        ),
        migrations.AddField(
            model_name='personage',
            name='animators_5_9_years',
            field=models.BooleanField(default=False, verbose_name='Аниматоры для 5-9 года'),
        ),
        migrations.AddField(
            model_name='personage',
            name='animators_9_14_years',
            field=models.BooleanField(default=False, verbose_name='Аниматоры для 9-14 года'),
        ),
    ]
