# Generated by Django 4.2.7 on 2023-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0001_initial'),
        ('personage', '0007_personage_animators_1_4_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personage',
            name='animators_1_4_years',
        ),
        migrations.RemoveField(
            model_name='personage',
            name='animators_5_9_years',
        ),
        migrations.RemoveField(
            model_name='personage',
            name='animators_9_14_years',
        ),
        migrations.AddField(
            model_name='personage',
            name='animators_for_years',
            field=models.ManyToManyField(blank=True, related_name='personages', to='age.age'),
        ),
    ]
