# Generated by Django 4.2.7 on 2023-11-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0008_remove_personage_animators_1_4_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personage',
            name='animators_for_years',
        ),
    ]
