# Generated by Django 4.2.4 on 2023-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0009_remove_personage_animators_for_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='personage_images/default.jpg', null=True, upload_to='personage_images', verbose_name='Фото')),
                ('activity', models.BooleanField(default=True, verbose_name='Активность')),
                ('life_size_puppet', models.BooleanField(default=False, verbose_name='Ростовая кукла')),
                ('personage1', models.ManyToManyField(blank=True, related_name='personagekombo1', to='personage.personage', verbose_name='Первый персонаж')),
                ('personage2', models.ManyToManyField(blank=True, related_name='personagekombo2', to='personage.personage', verbose_name='Второй персонаж')),
                ('personage3', models.ManyToManyField(blank=True, related_name='personagekombo3', to='personage.personage', verbose_name='Третий персонаж')),
            ],
        ),
    ]
