# Generated by Django 4.2.7 on 2023-11-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0010_kombo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kombo',
            name='personage3',
        ),
    ]
