# Generated by Django 4.2.7 on 2023-11-24 12:50

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0011_remove_kombo_personage3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kombo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_avatar_full_path),
        ),
        migrations.AlterField(
            model_name='personage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_avatar_full_path),
        ),
    ]
