# Generated by Django 4.2.7 on 2023-12-14 10:07

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0012_alter_kombo_image_alter_personage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kombo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_avatar_full_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='personage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_avatar_full_path, verbose_name='Изображение'),
        ),
    ]
