# Generated by Django 4.2.7 on 2023-12-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personage', '0013_alter_kombo_image_alter_personage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kombo',
            options={'verbose_name': 'Комбо', 'verbose_name_plural': 'Комбо'},
        ),
        migrations.AlterModelOptions(
            name='personage',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
    ]
