repos:
  - repo: https://github.com/omnilib/ufmt
    rev: v1.3.2
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 22.3
          - usort == 1.0.2

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

-   repo: https://github.com/pre-commit/pre-commit-hooks    
    rev: v4.4.0
    hooks:   
      - id: trailing-whitespace
      - id: end-of-file-fixer   
      - id: check-yaml
      - id: debug-statements  
      - id: double-quote-string-fixer
      - id: name-tests-test  
      - id: requirements-txt-fixer